// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Client struct {
	Public                 *bool             `json:"public,omitempty"`
	RedirectUris           []string          `json:"redirectUris,omitempty"`
	Description            *string           `json:"description,omitempty"`
	Name                   string            `json:"name"`
	Trusted                *bool             `json:"trusted,omitempty"`
	PostLogoutRedirectUris []string          `json:"postLogoutRedirectUris,omitempty"`
	Metadata               map[string]string `json:"metadata,omitempty"`
	Scopes                 []string          `json:"scopes,omitempty"`
	ID                     string            `json:"id"`
	Secrets                []ClientSecret    `json:"secrets,omitempty"`
}

func (o *Client) GetPublic() *bool {
	if o == nil {
		return nil
	}
	return o.Public
}

func (o *Client) GetRedirectUris() []string {
	if o == nil {
		return nil
	}
	return o.RedirectUris
}

func (o *Client) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Client) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Client) GetTrusted() *bool {
	if o == nil {
		return nil
	}
	return o.Trusted
}

func (o *Client) GetPostLogoutRedirectUris() []string {
	if o == nil {
		return nil
	}
	return o.PostLogoutRedirectUris
}

func (o *Client) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *Client) GetScopes() []string {
	if o == nil {
		return nil
	}
	return o.Scopes
}

func (o *Client) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Client) GetSecrets() []ClientSecret {
	if o == nil {
		return nil
	}
	return o.Secrets
}
