// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ClientSecret struct {
	LastDigits string         `json:"lastDigits"`
	Name       string         `json:"name"`
	ID         string         `json:"id"`
	Metadata   map[string]any `json:"metadata,omitempty"`
}

func (o *ClientSecret) GetLastDigits() string {
	if o == nil {
		return ""
	}
	return o.LastDigits
}

func (o *ClientSecret) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ClientSecret) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ClientSecret) GetMetadata() map[string]any {
	if o == nil {
		return nil
	}
	return o.Metadata
}
