// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Secret struct {
	Name       string            `json:"name"`
	Metadata   map[string]string `json:"metadata,omitempty"`
	ID         string            `json:"id"`
	LastDigits string            `json:"lastDigits"`
	Clear      string            `json:"clear"`
}

func (o *Secret) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Secret) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *Secret) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Secret) GetLastDigits() string {
	if o == nil {
		return ""
	}
	return o.LastDigits
}

func (o *Secret) GetClear() string {
	if o == nil {
		return ""
	}
	return o.Clear
}
