// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateClientRequest struct {
	Public                 *bool          `json:"public,omitempty"`
	RedirectUris           []string       `json:"redirectUris,omitempty"`
	Description            *string        `json:"description,omitempty"`
	Name                   string         `json:"name"`
	Trusted                *bool          `json:"trusted,omitempty"`
	PostLogoutRedirectUris []string       `json:"postLogoutRedirectUris,omitempty"`
	Metadata               map[string]any `json:"metadata,omitempty"`
	Scopes                 []string       `json:"scopes,omitempty"`
}

func (o *UpdateClientRequest) GetPublic() *bool {
	if o == nil {
		return nil
	}
	return o.Public
}

func (o *UpdateClientRequest) GetRedirectUris() []string {
	if o == nil {
		return nil
	}
	return o.RedirectUris
}

func (o *UpdateClientRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateClientRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateClientRequest) GetTrusted() *bool {
	if o == nil {
		return nil
	}
	return o.Trusted
}

func (o *UpdateClientRequest) GetPostLogoutRedirectUris() []string {
	if o == nil {
		return nil
	}
	return o.PostLogoutRedirectUris
}

func (o *UpdateClientRequest) GetMetadata() map[string]any {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *UpdateClientRequest) GetScopes() []string {
	if o == nil {
		return nil
	}
	return o.Scopes
}
