package audit

import (
	"fmt"
	"strings"
)

// Markdown renders the generated portion of the inventory: the derived totals
// and the per-family operation, baseline, scope, and risk tables.
//
// Prose, reasoning, and anything requiring judgement live in the hand-written
// docs/command-inventory.md. This function only tabulates facts the report
// already derived, so the two documents cannot drift into disagreeing.
func (r *Report) Markdown() string {
	var b strings.Builder

	b.WriteString("# Auth operation inventory (generated)\n\n")
	b.WriteString("<!-- Generated by plugins/fctl/cmd/specaudit. Do not edit by hand. -->\n")
	b.WriteString("<!-- Regenerate with `just fctl-audit`; verify with `just fctl-audit-check`. -->\n\n")

	fmt.Fprintf(&b, "Source document: `%s` (`%s` %s, OpenAPI %s, document version %s).\n\n",
		r.SpecDocument, r.Document.Title, r.Revisions.Product[:12], r.Document.OpenAPI, r.Document.Version)
	fmt.Fprintf(&b, "Legacy baseline: fctl `%s`. fctl-v2: `%s`.\n\n",
		r.Revisions.Baseline[:12], r.Revisions.FctlV2[:12])

	b.WriteString("## Totals\n\n")
	t := r.Totals
	b.WriteString("| Count | Value |\n|---|---:|\n")
	rows := []struct {
		label string
		value int
	}{
		{"Operations declared by the document", t.SpecOperations},
		{"Distinct operationIds", t.UniqueOperationIDs},
		{"Path items declared", t.SpecPaths},
		{"Deprecated operations", t.DeprecatedOperations},
		{"Included in the command facet", t.Included},
		{"Excluded from the command facet", t.Excluded},
		{"— included reads", t.Reads},
		{"— included writes", t.Writes},
		{"— included destructive", t.Destructive},
		{"— included sensitive", t.Sensitive},
		{"Legacy executable CLI paths", t.BaselinePaths},
		{"— canonical paths", t.BaselineCanonical},
		{"— duplicate-mount paths", t.BaselineDuplicate},
		{"— paths gated on approbation", t.BaselineConfirmedPaths},
		{"Distinct operations the baseline dispatches", t.BaselineOperations},
		{"Included operations with legacy precedent", t.IncludedWithBaseline},
		{"Included operations without legacy precedent", t.IncludedWithoutBaseline},
		{"Operations declaring a security block", t.ScopedOperations},
		{"— declaring exactly [auth:read]", t.ReadScoped},
		{"— declaring exactly [auth:write]", t.WriteScoped},
		{"Operations offering pagination", t.PaginatedOperations},
		{"Module-wide blockers", t.ModuleWideBlockers},
		{"Operations carrying a blocker", t.BlockedOperations},
		{"Recorded divergences", t.Divergences},
	}
	for _, row := range rows {
		fmt.Fprintf(&b, "| %s | %d |\n", row.label, row.value)
	}
	fmt.Fprintf(&b, "\nDeclared scopes: %s.\n\n", codeList(r.DeclaredScopes))

	b.WriteString("## Operations by family\n\n")
	byFamily := r.ByFamily()
	for _, family := range Families {
		recs := byFamily[family]
		if len(recs) == 0 {
			continue
		}
		fmt.Fprintf(&b, "### %s\n\n", family)
		b.WriteString("| operationId | Method | Path | Scopes | Success | Response | Request | Risk | Idempotence | Facet |\n")
		b.WriteString("|---|---|---|---|---|---|---|---|---|---|\n")
		for _, rec := range recs {
			fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s | %s | %s | %s | %s | %s | %s |\n",
				rec.OperationID, rec.Method, rec.Path,
				codeList(rec.Scopes), rec.SuccessCode,
				schemaCell(rec.SuccessBody), schemaCell(rec.RequestBody),
				rec.Risk, rec.Idempotence, facetCell(rec.Included))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Parameters\n\n")
	b.WriteString("| operationId | Parameters |\n|---|---|\n")
	for _, rec := range r.Operations {
		fmt.Fprintf(&b, "| `%s` | %s |\n", rec.OperationID, parameterCell(rec.Parameters))
	}
	b.WriteString("\n")

	b.WriteString("## Legacy baseline mapping\n\n")
	b.WriteString("Every included operation and the legacy fctl paths that reach it.\n\n")
	b.WriteString("| operationId | Legacy CLI paths | Approbation | Aliases |\n|---|---|---|---|\n")
	for _, rec := range r.Included() {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
			rec.OperationID, pathCell(rec.BaselineCommands),
			yesNo(rec.BaselineConfirmed), aliasCell(rec.OperationID))
	}
	b.WriteString("\n")

	b.WriteString("### Legacy command paths\n\n")
	b.WriteString("| Command path | operationId | Args | Approbation | Mount | Source |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, c := range Baseline {
		mount := "canonical"
		if c.Duplicate {
			mount = "duplicate"
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s | %s | `%s` |\n",
			c.Path, c.OperationID, c.Args, yesNo(c.Confirm), mount, c.Source)
	}
	b.WriteString("\n")

	b.WriteString("### Grouping-only nodes\n\n")
	b.WriteString("| Node | Aliases |\n|---|---|\n")
	for _, node := range []string{"auth", "auth clients", "auth clients secrets", "auth users"} {
		fmt.Fprintf(&b, "| `%s` | %s |\n", node, codeList(GroupAliases[node]))
	}
	b.WriteString("\n")

	b.WriteString("## Exclusions\n\n")
	b.WriteString("Operations the document declares that the command facet does not expose. ")
	b.WriteString("An exclusion is a scoping decision, not a blocker.\n\n")
	b.WriteString("| operationId | Owner | Reason |\n|---|---|---|\n")
	for _, e := range Exclusions {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", e.OperationID, e.Owner, oneLine(e.Reason))
	}
	fmt.Fprintf(&b, "\nDeprecations: none. The document marks %d operations deprecated.\n\n",
		r.Totals.DeprecatedOperations)

	b.WriteString("## Sensitive result\n\n")
	found := false
	for _, rec := range r.Operations {
		if rec.SensitivePointer == "" {
			continue
		}
		found = true
		fmt.Fprintf(&b, "`%s` returns clear-text credential material at JSON Pointer `%s` "+
			"in its %s response (`%s`). The field is declared *required*, so it is always "+
			"present on success, and the schema states the full value cannot be retrieved again.\n\n",
			rec.OperationID, rec.SensitivePointer, rec.SuccessCode, rec.SuccessBody)
	}
	if !found {
		b.WriteString("No operation returns clear-text credential material.\n\n")
	}

	b.WriteString("## Current admission blockers\n\n")
	if len(Blockers) == 0 {
		b.WriteString("No current admission blockers.\n\n")
	} else {
		b.WriteString("| ID | Scope | Statement |\n|---|---|---|\n")
		for _, bl := range Blockers {
			scope := "module-wide"
			if len(bl.OperationIDs) > 0 {
				scope = codeList(bl.OperationIDs)
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", bl.ID, scope, oneLine(bl.Statement))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Divergences\n\n")
	b.WriteString("| ID | Operations | Statement |\n|---|---|---|\n")
	for _, d := range Divergences {
		scope := "document-wide"
		if len(d.OperationIDs) > 0 {
			scope = codeList(d.OperationIDs)
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", d.ID, scope, oneLine(d.Statement))
	}

	return b.String()
}

// aliasCell renders the aliases of the baseline paths reaching the operation.
func aliasCell(operationID string) string {
	seen := map[string]struct{}{}
	var all []string
	for _, c := range Baseline {
		if c.OperationID != operationID {
			continue
		}
		for _, a := range c.Aliases {
			if _, dup := seen[a]; dup {
				continue
			}
			seen[a] = struct{}{}
			all = append(all, a)
		}
	}
	return codeList(all)
}

func codeList(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	quoted := make([]string, 0, len(items))
	for _, i := range items {
		quoted = append(quoted, "`"+i+"`")
	}
	return strings.Join(quoted, ", ")
}

func pathCell(items []string) string {
	if len(items) == 0 {
		return "— (no legacy precedent)"
	}
	return codeList(items)
}

func schemaCell(name string) string {
	if name == "" {
		return "— (none declared)"
	}
	return "`" + name + "`"
}

func parameterCell(params []Parameter) string {
	if len(params) == 0 {
		return "— (none)"
	}
	out := make([]string, 0, len(params))
	for _, p := range params {
		req := "optional"
		if p.Required {
			req = "required"
		}
		out = append(out, fmt.Sprintf("`%s` (%s, %s)", p.Name, p.In, req))
	}
	return strings.Join(out, ", ")
}

func facetCell(included bool) string {
	if included {
		return "command"
	}
	return "excluded"
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

// oneLine collapses a multi-line statement into a single table cell.
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}
