// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/auth/pkg/client/models/components"
)

type CreateClientResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Client created
	CreateClientResponse *components.CreateClientResponse
}

func (o *CreateClientResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateClientResponse) GetCreateClientResponse() *components.CreateClientResponse {
	if o == nil {
		return nil
	}
	return o.CreateClientResponse
}
