// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/auth/pkg/client/models/components"
)

type CreateSecretRequest struct {
	// Client ID
	ClientID            string                          `pathParam:"style=simple,explode=false,name=clientId"`
	CreateSecretRequest *components.CreateSecretRequest `request:"mediaType=application/json"`
}

func (o *CreateSecretRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *CreateSecretRequest) GetCreateSecretRequest() *components.CreateSecretRequest {
	if o == nil {
		return nil
	}
	return o.CreateSecretRequest
}

type CreateSecretResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created secret
	CreateSecretResponse *components.CreateSecretResponse
}

func (o *CreateSecretResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateSecretResponse) GetCreateSecretResponse() *components.CreateSecretResponse {
	if o == nil {
		return nil
	}
	return o.CreateSecretResponse
}
