// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/auth/pkg/client/models/components"
)

type DeleteClientRequest struct {
	// Client ID
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (o *DeleteClientRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

type DeleteClientResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteClientResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
