// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/auth/pkg/client/models/components"
)

type GetOIDCWellKnownsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetOIDCWellKnownsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
