// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/auth/pkg/client/models/components"
)

type UpdateClientRequest struct {
	// Client ID
	ClientID            string                          `pathParam:"style=simple,explode=false,name=clientId"`
	UpdateClientRequest *components.UpdateClientRequest `request:"mediaType=application/json"`
}

func (o *UpdateClientRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *UpdateClientRequest) GetUpdateClientRequest() *components.UpdateClientRequest {
	if o == nil {
		return nil
	}
	return o.UpdateClientRequest
}

type UpdateClientResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Updated client
	UpdateClientResponse *components.UpdateClientResponse
}

func (o *UpdateClientResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateClientResponse) GetUpdateClientResponse() *components.UpdateClientResponse {
	if o == nil {
		return nil
	}
	return o.UpdateClientResponse
}
