/*
Auth API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: AUTH_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authclient

import (
	"encoding/json"
)

// ManyScopesResponse struct for ManyScopesResponse
type ManyScopesResponse struct {
	Data []Scope `json:"data,omitempty"`
}

// NewManyScopesResponse instantiates a new ManyScopesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManyScopesResponse() *ManyScopesResponse {
	this := ManyScopesResponse{}
	return &this
}

// NewManyScopesResponseWithDefaults instantiates a new ManyScopesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManyScopesResponseWithDefaults() *ManyScopesResponse {
	this := ManyScopesResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ManyScopesResponse) GetData() []Scope {
	if o == nil || o.Data == nil {
		var ret []Scope
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManyScopesResponse) GetDataOk() ([]Scope, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ManyScopesResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []Scope and assigns it to the Data field.
func (o *ManyScopesResponse) SetData(v []Scope) {
	o.Data = v
}

func (o ManyScopesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableManyScopesResponse struct {
	value *ManyScopesResponse
	isSet bool
}

func (v NullableManyScopesResponse) Get() *ManyScopesResponse {
	return v.value
}

func (v *NullableManyScopesResponse) Set(val *ManyScopesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManyScopesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManyScopesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManyScopesResponse(val *ManyScopesResponse) *NullableManyScopesResponse {
	return &NullableManyScopesResponse{value: val, isSet: true}
}

func (v NullableManyScopesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManyScopesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


