/*
Auth API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: AUTH_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authclient

import (
	"encoding/json"
)

// OneScopeResponse struct for OneScopeResponse
type OneScopeResponse struct {
	Data *Scope `json:"data,omitempty"`
}

// NewOneScopeResponse instantiates a new OneScopeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOneScopeResponse() *OneScopeResponse {
	this := OneScopeResponse{}
	return &this
}

// NewOneScopeResponseWithDefaults instantiates a new OneScopeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOneScopeResponseWithDefaults() *OneScopeResponse {
	this := OneScopeResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OneScopeResponse) GetData() Scope {
	if o == nil || o.Data == nil {
		var ret Scope
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OneScopeResponse) GetDataOk() (*Scope, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OneScopeResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given Scope and assigns it to the Data field.
func (o *OneScopeResponse) SetData(v Scope) {
	o.Data = &v
}

func (o OneScopeResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableOneScopeResponse struct {
	value *OneScopeResponse
	isSet bool
}

func (v NullableOneScopeResponse) Get() *OneScopeResponse {
	return v.value
}

func (v *NullableOneScopeResponse) Set(val *OneScopeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOneScopeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOneScopeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOneScopeResponse(val *OneScopeResponse) *NullableOneScopeResponse {
	return &NullableOneScopeResponse{value: val, isSet: true}
}

func (v NullableOneScopeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOneScopeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


