/*
Auth API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: AUTH_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authclient

import (
	"encoding/json"
)

// OneUserResponse struct for OneUserResponse
type OneUserResponse struct {
	Data *User `json:"data,omitempty"`
}

// NewOneUserResponse instantiates a new OneUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOneUserResponse() *OneUserResponse {
	this := OneUserResponse{}
	return &this
}

// NewOneUserResponseWithDefaults instantiates a new OneUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOneUserResponseWithDefaults() *OneUserResponse {
	this := OneUserResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OneUserResponse) GetData() User {
	if o == nil || o.Data == nil {
		var ret User
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OneUserResponse) GetDataOk() (*User, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OneUserResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given User and assigns it to the Data field.
func (o *OneUserResponse) SetData(v User) {
	o.Data = &v
}

func (o OneUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableOneUserResponse struct {
	value *OneUserResponse
	isSet bool
}

func (v NullableOneUserResponse) Get() *OneUserResponse {
	return v.value
}

func (v *NullableOneUserResponse) Set(val *OneUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOneUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOneUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOneUserResponse(val *OneUserResponse) *NullableOneUserResponse {
	return &NullableOneUserResponse{value: val, isSet: true}
}

func (v NullableOneUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOneUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


